[package]
name = "bevy_retro"
version = "0.1.0"
authors = ["Katharos Technology LLC."]
edition = "2018"

license-file = "LICENSE.md"
readme = "README.md"
description = "Pixel-Perfect, 2D Renderer and plugins for Bevy that Seamlessly Targets Desktop and Web"
repository = "https://github.com/katharostech/bevy_retro"
documentation = "https://docs.rs/bevy_retro"
keywords = ["bevy", "gamedev", "2D", "bevy_retro", "pixel-perfect"]
categories = [
    "game-engines",
    "multimedia",
    "rendering::engine",
    "wasm"
]

[workspace]
members = ["crates/*"]

[features]
default = [
    "audio",
    "text",
    "ui",
]
audio = ["bevy_retro_audio"]
text = ["bevy_retro_text"]
ui = ["bevy_retro_ui"]

ldtk = ["bevy_retro_ldtk"]

[dependencies]
bevy = { version = "0.5", default-features = false }
bevy_retro_macros = { version = "0.1", path = "crates/bevy_retro_macros" }
bevy_retro_core = { version = "0.1", path = "crates/bevy_retro_core" }
bevy_retro_audio = { version = "0.1", path = "crates/bevy_retro_audio", optional = true }
bevy_retro_ldtk = { version = "0.1", path = "crates/bevy_retro_ldtk", optional = true }
bevy_retro_text = { version = "0.1", path = "crates/bevy_retro_text", optional = true }
bevy_retro_ui = { version = "0.1", path = "crates/bevy_retro_ui", optional = true }

[dev-dependencies]
hex = "0.4.3"
rand = "0.8.3"

[profile.dev]
opt-level = 3
debug = 1

[profile.release]
lto = true

# Add LDtk example explicitly so we can say it requires the ldtk feature
[[example]]
name = "ldtk_map"
path = "examples/ldtk_map.rs"
required-features = ["ldtk"]
