[package]
name = "bevy_retro"
version = "0.0.0"
authors = ["Zicklag <zicklag@katharostech.com>"]
edition = "2018"

[workspace]
members = ["crates/*"]

[features]
default = [
    "audio",
    "text",
    "ui",
]
audio = ["bevy_retro_audio"]
text = ["bevy_retro_text"]
ui = ["bevy_retro_ui"]

ldtk = ["bevy_retro_ldtk"]

[dependencies]
bevy = { version = "0.5", default-features = false }
bevy_retro_macros = { path = "crates/bevy_retro_macros" }
bevy_retro_core = { path = "crates/bevy_retro_core" }
bevy_retro_audio = { path = "crates/bevy_retro_audio", optional = true }
bevy_retro_ldtk = { path = "crates/bevy_retro_ldtk", optional = true }
bevy_retro_text = { path = "crates/bevy_retro_text", optional = true }
bevy_retro_ui = { path = "crates/bevy_retro_ui", optional = true }

[dev-dependencies]
hex = "0.4.3"
rand = "0.8.3"

[profile.dev]
opt-level = 3
debug = 1

[profile.release]
lto = true

[[example]]
name = "ldtk_map"
path = "examples/ldtk_map.rs"
required-features = ["ldtk"]
