name: Build & Test

on:
  push:
    branches: [ master, staging, trying ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'

      - name: Cargo Registry Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-registry

      - name: Check
        run: cargo check --workspace --features ldtk
      - name: Clippy
        run: cargo clippy --workspace --features ldtk

  build-and-test-native:
    needs: check
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
        toolchain: [ 'stable', 'nightly' ]
    continue-on-error: ${{ matrix.toolchain == 'nightly' }}
    env:
      # Override the Cargo.toml dev profile settings to optimize for build speed
      CARGO_PROFILE_DEV_DEBUG: 'true'
      CARGO_PROFILE_DEV_OPT_LEVEL: '0'
      # Disable incremental builds to hopefully reduce the cache size and avoid GitHub purging
      # the caches so much and therefore causing cache misses
      CARGO_INCREMENTAL: '0'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Install alsa and udev
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
        if: runner.os == 'linux'

      - name: Cargo Registry Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-registry

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Build
        run: cargo build --workspace --features ldtk --verbose

      - name: Test
        run: cargo test --workspace --features ldtk --verbose

  build-wasm:
    needs: check
    runs-on: ubuntu-latest
    env:
      # Override the Cargo.toml dev profile settings to optimize for build speed
      CARGO_PROFILE_DEV_DEBUG: 'true'
      CARGO_PROFILE_DEV_OPT_LEVEL: '0'
      # Disable incremental builds to hopefully reduce the cache size and avoid GitHub purging
      # the caches so much and therefore causing cache misses
      CARGO_INCREMENTAL: '0'
    steps:
      - uses: actions/checkout@v2

      - name: Cargo Registry Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
          key: cargo-registry

      - name: Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Build
        run: cargo build --workspace --features ldtk --verbose --target wasm32-unknown-unknown
